### ISSUE TITLE
jQuery-1.9.0.jsにてIllegal invocationエラー。

### ISSUE THREAD

**Issue by tantanntan** [ics-opendev/nsys#115]
@icmurase saids.
`
jquery-1.9.0.js:7309 Uncaught TypeError: Illegal invocation(…)add @ jquery-1.9.0.js:7309buildParams @ jquery-1.9.0.js:7361jQuery.param @ jquery-1.9.0.js:7329ajax @ jquery-1.9.0.js:7815(anonymous function) @ cs.acceptance.js:771serverResponded @ sails.io.js:282Socket.onack @ sails.io.js:3Socket.onpacket @ sails.io.js:3(anonymous function) @ sails.io.js:3Emitter.emit @ sails.io.js:3Manager.ondecoded @ sails.io.js:3(anonymous function) @ sails.io.js:3Emitter.emit @ sails.io.js:3Decoder.add @ sails.io.js:5Manager.ondata @ sails.io.js:3(anonymous function) @ sails.io.js:3Emitter.emit @ sails.io.js:3Socket.onPacket @ sails.io.js:3(anonymous function) @ sails.io.js:3Emitter.emit @ sails.io.js:3Transport.onPacket @ sails.io.js:3Transport.onData @ sails.io.js:3ws.onmessage @ sails.io.js:4
`

**Comment by tantanntan** [comment]
@icmurase  とりあえず、これ呼んでるいまのcs.acceptance.jsが見たいなあ。

**Comment by watanabk** [comment]
@icmurase 
解決済みですが、備忘としてメモ。

```javascript
var mime_base64 = img.src.split(',', 2);
var mime = mime_base64[0].split(';');
mime = mime[0].split(':');
mime = mime[1]? mime[1]: mime[0];
var base64 = window.atob(mime_base64[1]);
var len = base64.length;
var bin = new Uint8Array(len);
for (var i=0; i<len; i++)
{
  bin[i] = base64.charCodeAt(i);
}
var blob = new Blob([bin], {type:mime});
```
BLOB生成処理を下記の通り修正し、$.Ajax options に processData: false を追加。
```javascript
var mime = data_url_scheme.split(',')[0].split(':')[1].split(';')[0];
var bin = atob(data_url_scheme.split(',')[1]);
var buffer = new Uint8Array(bin.length);
for (var i = 0; i < bin.length; i++) 
{
	buffer[i] = bin.charCodeAt(i);
}
var blob = new Blob([buffer], {type: mime});
```

その後下記エラーが発生
```
POST https://api.projectoxford.ai/face/v1.0/persongroups/group03/persons/cd8da7df-d6c1-4ec9-bb73-40849e6e00c7/persistedFaces 400 (Bad Request)
Object {readyState: 4, responseText: "{"error":{"code":"InvalidImage","message":"No face detected in the image."}}", status: 400, statusText: "Bad Request"}
```
原因は、アップロードした画像ファイルから顔を検出することができなかったため。
